"""empty message

Revision ID: 0c9a8b79f05e
Revises: f5afcd64c8c3
Create Date: 2021-03-10 02:07:08.356693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9a8b79f05e'
down_revision = 'f5afcd64c8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_category_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'category', ['category'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_category_fkey', 'item', 'category', ['category'], ['name'])
    # ### end Alembic commands ###
