"""empty message

Revision ID: 741dd2e3276f
Revises: 307122429827
Create Date: 2021-03-05 19:30:29.587762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741dd2e3276f'
down_revision = '307122429827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'category', ['category'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
