"""empty message

Revision ID: 868a72c5407c
Revises: 0c9a8b79f05e
Create Date: 2021-03-17 20:20:59.628755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868a72c5407c'
down_revision = '0c9a8b79f05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('quantities_next', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'quantities_next')
    # ### end Alembic commands ###
